fix rvm/PATH issue across linux/OSX, update tmux startup script

diff --git a/scripts/tmux-oss b/scripts/tmux-oss
--- a/scripts/tmux-oss
+++ b/scripts/tmux-oss
@@ -8,10 +8,10 @@ if [ $# -eq 1 ]
 then
     if [ -d $1 ]
     then
-	cd $1
+        cd $1
     else
-	echo "directory $1 not found"
-	exit 1
+        echo "directory $1 not found"
+        exit 1
     fi
 fi
 
@@ -53,9 +53,7 @@ else
     # for send-keys, it will first try to interpret the session name as a
     # window identifier.  Which we don't want.
 
-    tmux new-session -s "$PROJECT" -d -n server
-    tmux new-window -t "$PMATCH"
-    tmux send-keys   -t "$PMATCH:" "cd ~/Projects/OfficeSpace/huddle; teamocil --here --layout huddle-react.yml" C-m
-
+    tmux new-session -s "$PROJECT" -d -n "$PMATCH"
+    tmux send-keys -t "$PMATCH:" "teamocil --here --layout huddle-react.yml" C-m
     tmux attach-session -t "$PMATCH"
 fi
